### ISSUE TITLE
Synopsis code doesn't reproduce example output

### ISSUE THREAD

**Issue by djerius** [polettix/App-Easer#1]
Perl 5.28
App::Easer 0.010

Running the code in the Synopsis doesn't result in the expected output.  I've put the code I've copied from the Synopsis [here](https://gist.github.com/djerius/dbcac75cda886e7791402c776a3520bc).   Here are the results:
```
% perl example.pl
Hello, bar!
% perl example.pl --foo World
Hello, World!
% perl example.pl commands
Hello, bar!
% perl example.pl help
Hello, bar!
```
`help` and `commands` don't seem to work.  The `tudu` example application seems to work fine.

**Comment by djerius** [comment]
Aha.  It seems that one needs to add `'auto-leaves' => 0` to the configuration.

**Comment by polettix** [comment]
You're right, I forgot to update the SYNOPSIS after setting a different default for `auto-leaves`.

I'll think about releasing a new V1 with the correct message, although I'm actually working on V2 now.
