### ISSUE TITLE
RFE: A little less help

### ISSUE THREAD

**Issue by djerius** [polettix/App-Easer#12]
My understanding of the distinction between the `help` and `description` entries is that `description` is more like the manual page and `help` is there to remind the user how to run it (e.g. options, arguments, etc).

However, issuing the `help` command outputs the (often voluminous) `description` for a command, which makes it very difficult to get an overview of the application or the options.

For example, here's what I get for an application with a top level command and a subcommand:

```
% cxc-deroll help 
deroll an observation

Description:
    cxc-deroll [options] <directory>
    
    Process an observation in <directory> so that the Sky (X,Y)
    coordinates are aligned with the telescope's (Y,Z)
    coordinates.  The pointing and nominal RA, DEC, and ROLL are
    set to 0h, 0°, 0°.
    
    The resultant reprocessed files are found in <directory/repro>,
    unless the <--outdir> option is specified.
    
    The aspect solution files are modified and a modified version
    of CIAO's <chandra_repro> is invoked to process the data with
    the modified aspect files.
    
    At present, grating data are not correctly processed to the EVT2
    stage.
    
    While some files are modified during this process, they should all

Options:
        verbose: be talkative
                 command-line: integer, value is required
                               --verbose <value>
                               -v <value>
                      default: 0

         outdir: Output directory [default = <directory>/repro]
                 command-line: string, value is required
                               --outdir <value>

           help: 
                 command-line: boolean
                               --help
                               -h

Sub-commands:
    deroll-asol: deroll one or more aspect files "in place"
           help: print a help command
       commands: list sub-commands
           tree: print sub-commands in a tree
```
That's a lot to wade through.  It'd be useful if there was another level of help (usage?) which would output the `help` text and the options.

That brings up an inconsistency in documentation of non-option arguments.  Currently I put them in the `description` text, as it would be inconsistent to have them in the `help` text, as the options don't appear there.

However, putting them in `description` prevents one from having the "intermediate" level of documentation I suggest above.  I think there needs to be a specific mechanism to document non-option command line arguments so that they will be automatically and consistently output with the option arguments.

**Comment by polettix** [comment]
Hi! The *help* part is mainly aimed at the list of sub-commands as a quick hint of what's inside the box, and I've used the description part for the non-named options too.

It's surely possible to add something to provide help for non-option stuff, although I'm not sure whether it's better to use a specific key for it or do something different (e.g. an "option" without the getopt key).

Regarding the first question, this might be introduced as an option to the help command itself.

**Comment by polettix** [comment]
Commits https://github.com/polettix/App-Easer/commit/ca39d16954610095b7e90d9f08864fe9effb6bbf and https://github.com/polettix/App-Easer/commit/c8a8d91a1682613934c880d8d93e7fe2d277e46e should address the need.

It is now possible to add a `usage` key/value pair to set text related to... usage. This is printed after the Description.

In addition to `help` there is an alias `usage` that does *not* print the Description.

It is also possible to set options_help to either a string (totally substitutes the Options section, no auto-generation happens) or to a hash reference with keys `preamble` and `postamble` that should do what they mean.

**Comment by polettix** [comment]
[Release v2.008 is out](https://metacpan.org/release/POLETTIX/App-Easer-2.008)
