### ISSUE TITLE
Please document "sources" subroutine interface

### ISSUE THREAD

**Issue by djerius** [polettix/App-Easer#14]
Hi,

The API for a custom locator subroutine isn't defined. Given a locator of 

`[ \&locator, @opts ]`

it seems to be

    sub locator( $app, \@opts, \@args );

where `@args` is an undocumented argument to `collect`, which receives it from `run`, which receives it as the list of arguments to parse.

None of the provided source_* routines make use of `@args`; is its presence in their signature a deprecated pattern?

**Comment by djerius** [comment]
> None of the provided source_* routines make use of `@args`; is its presence in their signature a deprecated pattern?

I missed that source_CmdLine does use it.

**Comment by polettix** [comment]
Yep... that needs some documentation, I'd like to coalesce this with #13 if possible...

**Comment by polettix** [comment]
Should be fixed by 8e22238fefe7f8c90ec7d604d508b58b0092191f

**Comment by polettix** [comment]
[Release v2.008 is out](https://metacpan.org/release/POLETTIX/App-Easer-2.008)
