### ISSUE TITLE
Obtaining top-level help without subcommands? or, how to implement --help?

### ISSUE THREAD

**Issue by djerius** [polettix/App-Easer#2]
My understanding of App::Easer is that help is supported only through the `help` subcommand. 

If an application doesn't have subcommands (e.g. it uses  all of the command line arguments for its own purposes) then I'm not sure how to trigger the help output.

Traditionally there'd be a `--help` option at the top level to provide help, but its not clear if it's possible to access the help facility outside of the `help` subcommand.  In other words, I'd like `--help` to be an alias for the `help` command.

**Comment by polettix** [comment]
Thanks for your interest and for asking questions!

> NOTE: I'm refactoring App::Easer into versioning and working on version 2 in a separate branch. I've been using V2 for some months and it does what I need, so I'd like to release it as soon as I set some more tests up (e.g. see [here][]).

In V1 you can leverage the `commit` hook to fiddle with `$args` and trigger going down for the `help` sub-command in case option `--help` is present.

```perl
#!/usr/bin/env perl
use v5.24;
use experimental 'signatures';
use App::Easer 'run';
my $app = {
   configuration => {
      'auto-leaves' => 0,
      'auto-children' => ['help'],
   },
   commands => {
      MAIN => {
         name => 'main app',
         help => 'this is the main app',
         description => 'Yes, this really is the main app',
         options => [
            {
               name => 'foo',
               help => 'option foo!',
               getopt => 'foo|f=s',
               environment => 'FOO',
               default => 'bar',
            },
            {
               getopt => 'help!',
               help => 'get help on command',
            },
         ],
         execute => sub ($global, $conf, $args) {
            my @unparsed_args = $global->{configs}[-1]{all_args}->@*;
            my $foo = $conf->{foo};
            say "Hello, $foo! (@unparsed_args)";
            return 0;
         },
         commit => sub ($global, $spec, $args) {
            my $conf = $global->{configs}[-1];
            $conf->{all_args} = [splice $args->@*, 0];
            $args->@* = 'help' if $conf->{help};
         },
         'default-child' => '', # run execute by default
      },
   },
};
exit run($app, [@ARGV]);
```

This might be used for `--commands` too, although in this case it would not make too much sense... This is also why I've added the `auto-children` in the `configuration` section.

Sample run:

```
$ perl cmdhelp.pl --help 
this is the main app

Description:
    Yes, this really is the main app

Options:
            foo: option foo!
                 command-line: mandatory string option
                               --foo <value>
                               -f <value>
                 environment : FOO
                 default     : bar

           help: get help on command
                 command-line: boolean option
                               --help | --no-help

Sub commands:
           help: print a help message

$ perl cmdhelp.pl help everybody
Hello, bar! (help everybody)
```

Well... `help` still appears as a sub-command in the help message, but you get what you pay for 😁 


[here]: https://github.polettix.it/ETOOBUSY/2022/03/08/app-easer-more-tests/

**Comment by polettix** [comment]
(I'll look for a way to do this in a documented way in V2, thanks for raising this issue!)

**Comment by djerius** [comment]
Thanks!

> NOTE: I'm refactoring App::Easer into versioning and working on version 2 in a separate branch. I've been using V2 for some months and it does what I need, so I'd like to release it as soon as I set some more tests up (e.g. see [here](https://github.polettix.it/ETOOBUSY/2022/03/08/app-easer-more-tests/)).

Your blog is where I came across App::Easer.  Finding it on CPAN is nigh on to impossible (what does one search for?).  Don't ask me how I stumbled across your blog.

**Comment by polettix** [comment]
This is how you would do it in V2 ([test here][]):

```perl
sub execute ($self) {
   return $self->run_help if $self->config('help');
   say 'normal call <', join('> <', $self->residual_args), '>';
   return 0;
} ## end sub execute
```

There is also a `$self->full_help_text` call available to get just the text of the help and use as you see fit (e.g. if you want to pipe that into `less` directly from your code, or put a frame around it, or whatever).

Thanks again for reminding me about this (the basic stuff was already there, just needed testing and documentation).

[test here]: https://github.com/polettix/App-Easer/blob/versioning/t/V2/06.help-as-option.t
