### ISSUE TITLE
Help message for Boolean option incorrectly indicates it takes a value

### ISSUE THREAD

**Issue by djerius** [polettix/App-Easer#5]
Hi,
Given an Boolean option specification, e.g. `'help|h'`, the help output             

```
                 command-line: --help <value>
                               -h <value>
```
indicates it requires a value.  Changing it to `'help|h!'` results in a more correct output:

```
                 command-line: boolean option
                               --help | --no-help
                               -h
```
but unfortunately introduces an unwanted `--no-help` option.

**Comment by polettix** [comment]
TIL that there are **two** ways of specifying boolean options in Getopt::Long and actually made sense of why `!` is used. Thank you so much.

As with the #4, please prod me if you don't hear back in a couple of weeks. Thanks!

**Comment by polettix** [comment]
This should be solved now... please reopen if this is not the case!

**Comment by djerius** [comment]
Thanks!
