### ISSUE TITLE
incorrect documentation for residual_args' argument

### ISSUE THREAD

**Issue by djerius** [polettix/App-Easer#8]
The documentation for `residual_args` indicates it takes an array, but it actually takes an array reference.

**Comment by polettix** [comment]
Thanks, I noticed this same thing in the past days and I didn't even go to look for it in the docs, I just assumed I was using it the wrong way.

I'm not 100% happy with the "disconnect" between the input and the output interface (list vs array-ref), but I guess at this point it's better to leave the behaviour as it is and correct the docs as suggested.

**Comment by polettix** [comment]
Fixed by 2862d48, will be in next release.

**Comment by polettix** [comment]
[Release v2.008 is out](https://metacpan.org/release/POLETTIX/App-Easer-2.008)
